// NexusSearch — Mock Graph Data
// Used during development and as demo fallback if API is unavailable.
// Mirrors the exact structure returned by the FastAPI backend.

import { GraphResponse } from "@/types/graph";

export const MOCK_GRAPH: GraphResponse = {
  query: "Economic history of India",
  summary:
    "India's economic history spans millennia, from one of the world's wealthiest civilizations during the Mughal era to colonial exploitation under the British East India Company, followed by post-independence socialist planning and the transformative 1991 liberalization that opened India to global markets. Today India is the world's fifth-largest economy, driven by services, technology, and a growing manufacturing sector.",
  node_count: 18,
  edge_count: 22,
  cached: false,
  nodes: [
    // ── Query Root ─────────────────────────────────────────────────────
    {
      id: "query::economic history of india",
      name: "Economic History of India",
      type: "CONCEPT",
      description: "The central research topic spanning ancient trade, colonial era, and modern economy.",
      relevance_score: 1.0,
      is_query_node: true,
      neighbor_count: 8,
      val: 8.0,
      color: "#00D4FF",
    },
    // ── Core Concepts ──────────────────────────────────────────────────
    {
      id: "mughal-empire",
      name: "Mughal Empire",
      type: "ORGANIZATION",
      description: "At its peak the Mughal Empire accounted for ~25% of world GDP, making it one of history's wealthiest empires.",
      relevance_score: 0.88,
      is_query_node: false,
      neighbor_count: 4,
      val: 3.64,
      color: "#A78BFA",
      source_url: "https://en.wikipedia.org/wiki/Mughal_Empire",
    },
    {
      id: "british-east-india-company",
      name: "British East India Company",
      type: "ORGANIZATION",
      description: "A joint-stock company that systematically extracted wealth from the Indian subcontinent between 1757–1858, reshaping its economy irreversibly.",
      relevance_score: 0.92,
      is_query_node: false,
      neighbor_count: 5,
      val: 3.76,
      color: "#A78BFA",
      source_url: "https://en.wikipedia.org/wiki/East_India_Company",
    },
    {
      id: "1991-liberalization",
      name: "1991 Liberalization",
      type: "EVENT",
      description: "A landmark economic reform triggered by a balance-of-payments crisis, dismantling the License Raj and integrating India into the global economy.",
      relevance_score: 0.95,
      is_query_node: false,
      neighbor_count: 4,
      val: 3.85,
      color: "#F59E0B",
      source_url: "https://en.wikipedia.org/wiki/1991_Indian_economic_crisis",
    },
    {
      id: "manmohan-singh",
      name: "Manmohan Singh",
      type: "PERSON",
      description: "Finance Minister during the 1991 reforms, later Prime Minister; the architect of India's modern open-market economy.",
      relevance_score: 0.85,
      is_query_node: false,
      neighbor_count: 3,
      val: 3.55,
      color: "#60A5FA",
      source_url: "https://en.wikipedia.org/wiki/Manmohan_Singh",
    },
    {
      id: "license-raj",
      name: "License Raj",
      type: "CONCEPT",
      description: "The elaborate system of regulations, licenses, and red tape that governed the Indian economy from 1947 to 1990, stifling growth and entrepreneurship.",
      relevance_score: 0.82,
      is_query_node: false,
      neighbor_count: 3,
      val: 3.46,
      color: "#34D399",
    },
    {
      id: "nehru-industrial-policy",
      name: "Nehruvian Socialism",
      type: "CONCEPT",
      description: "Jawaharlal Nehru's vision of state-led industrialization and central planning that dominated India's economic policy from 1947–1991.",
      relevance_score: 0.80,
      is_query_node: false,
      neighbor_count: 3,
      val: 3.4,
      color: "#34D399",
    },
    {
      id: "green-revolution",
      name: "Green Revolution",
      type: "EVENT",
      description: "The 1960s agricultural transformation led by M.S. Swaminathan that made India self-sufficient in food production through high-yield crop varieties.",
      relevance_score: 0.75,
      is_query_node: false,
      neighbor_count: 2,
      val: 3.25,
      color: "#F59E0B",
    },
    {
      id: "it-boom",
      name: "IT & Services Boom",
      type: "EVENT",
      description: "The explosion of India's technology sector in the 1990s–2000s, anchored in Bangalore, that made India a global back-office and software powerhouse.",
      relevance_score: 0.78,
      is_query_node: false,
      neighbor_count: 3,
      val: 3.34,
      color: "#F59E0B",
    },
    {
      id: "battle-of-plassey",
      name: "Battle of Plassey (1757)",
      type: "EVENT",
      description: "The British East India Company's victory that established British dominance over Bengal, marking the beginning of colonial economic control.",
      relevance_score: 0.72,
      is_query_node: false,
      neighbor_count: 2,
      val: 3.16,
      color: "#F59E0B",
    },
    {
      id: "jawaharlal-nehru",
      name: "Jawaharlal Nehru",
      type: "PERSON",
      description: "India's first Prime Minister whose vision of a mixed socialist economy shaped India's development model for four decades post-independence.",
      relevance_score: 0.78,
      is_query_node: false,
      neighbor_count: 3,
      val: 3.34,
      color: "#60A5FA",
    },
    {
      id: "world-bank-imf",
      name: "World Bank / IMF",
      type: "ORGANIZATION",
      description: "International institutions that provided conditional emergency loans to India during the 1991 crisis, catalyzing structural reform.",
      relevance_score: 0.68,
      is_query_node: false,
      neighbor_count: 2,
      val: 3.04,
      color: "#A78BFA",
    },
    {
      id: "infosys",
      name: "Infosys",
      type: "ORGANIZATION",
      description: "Founded in 1981, Infosys became a symbol of India's IT sector rise and its capacity to compete globally in knowledge-based services.",
      relevance_score: 0.60,
      is_query_node: false,
      neighbor_count: 2,
      val: 2.8,
      color: "#A78BFA",
    },
    {
      id: "bengal-famine",
      name: "Bengal Famine (1943)",
      type: "EVENT",
      description: "A catastrophic famine that killed 2–3 million people, largely attributed to colonial economic policies and wartime resource extraction.",
      relevance_score: 0.65,
      is_query_node: false,
      neighbor_count: 2,
      val: 2.95,
      color: "#F87171",
    },
    {
      id: "narasimha-rao",
      name: "P.V. Narasimha Rao",
      type: "PERSON",
      description: "Prime Minister who alongside Manmohan Singh initiated the 1991 reforms, breaking from decades of socialist orthodoxy.",
      relevance_score: 0.72,
      is_query_node: false,
      neighbor_count: 2,
      val: 3.16,
      color: "#60A5FA",
    },
    {
      id: "bangalore",
      name: "Bangalore",
      type: "PLACE",
      description: "India's Silicon Valley — the city that became the geographic hub of India's technology and startup economy.",
      relevance_score: 0.55,
      is_query_node: false,
      neighbor_count: 2,
      val: 2.65,
      color: "#F87171",
    },
    {
      id: "make-in-india",
      name: "Make in India",
      type: "CONCEPT",
      description: "Modi government's 2014 initiative to transform India into a global manufacturing hub, seeking to replicate China's factory-of-the-world model.",
      relevance_score: 0.58,
      is_query_node: false,
      neighbor_count: 1,
      val: 2.74,
      color: "#34D399",
    },
    {
      id: "india-gdp-2024",
      name: "5th Largest Economy",
      type: "CONCEPT",
      description: "By 2023, India surpassed the UK to become the world's 5th largest economy by GDP, with projections to reach 3rd by 2030.",
      relevance_score: 0.62,
      is_query_node: false,
      neighbor_count: 1,
      val: 2.86,
      color: "#34D399",
    },
  ],
  edges: [
    // Spokes from root
    { source: "query::economic history of india", target: "mughal-empire",              relationship: "INCLUDES_ERA",    weight: 2.0 },
    { source: "query::economic history of india", target: "british-east-india-company", relationship: "INCLUDES_ERA",    weight: 2.5 },
    { source: "query::economic history of india", target: "1991-liberalization",         relationship: "KEY_EVENT",       weight: 3.0 },
    { source: "query::economic history of india", target: "nehru-industrial-policy",     relationship: "INCLUDES_ERA",    weight: 2.0 },
    { source: "query::economic history of india", target: "green-revolution",            relationship: "KEY_EVENT",       weight: 1.8 },
    { source: "query::economic history of india", target: "it-boom",                     relationship: "KEY_EVENT",       weight: 2.0 },
    { source: "query::economic history of india", target: "license-raj",                 relationship: "DEFINING_SYSTEM", weight: 2.2 },
    { source: "query::economic history of india", target: "india-gdp-2024",              relationship: "CURRENT_STATUS",  weight: 1.5 },
    // Entity-to-entity
    { source: "british-east-india-company", target: "battle-of-plassey",    relationship: "WON",           weight: 2.5 },
    { source: "british-east-india-company", target: "bengal-famine",        relationship: "CAUSED",        weight: 2.0 },
    { source: "british-east-india-company", target: "mughal-empire",        relationship: "REPLACED",      weight: 2.0 },
    { source: "jawaharlal-nehru",           target: "nehru-industrial-policy", relationship: "AUTHORED",   weight: 3.0 },
    { source: "nehru-industrial-policy",    target: "license-raj",          relationship: "CREATED",       weight: 2.5 },
    { source: "license-raj",               target: "1991-liberalization",   relationship: "ABOLISHED_BY",  weight: 2.5 },
    { source: "manmohan-singh",            target: "1991-liberalization",   relationship: "ARCHITECTED",   weight: 3.0 },
    { source: "narasimha-rao",             target: "1991-liberalization",   relationship: "AUTHORIZED",    weight: 2.5 },
    { source: "world-bank-imf",            target: "1991-liberalization",   relationship: "TRIGGERED",     weight: 2.0 },
    { source: "1991-liberalization",       target: "it-boom",               relationship: "ENABLED",       weight: 2.5 },
    { source: "it-boom",                   target: "infosys",               relationship: "INCLUDES",      weight: 2.0 },
    { source: "it-boom",                   target: "bangalore",             relationship: "CENTERED_IN",   weight: 1.8 },
    { source: "india-gdp-2024",            target: "make-in-india",         relationship: "DRIVEN_BY",     weight: 1.5 },
    { source: "jawaharlal-nehru",          target: "nehru-industrial-policy", relationship: "CHAMPIONED",  weight: 2.0 },
  ],
};
